### PR TITLE
Fixed truncated answer

### PR DESCRIPTION
**Pull request by Miniwoffer**
When an answer is truncaned retry with TCP.
see #111 tests are in #112 but they are a little race-conditiony, so unsure if they should be merged.

### CODE REVIEW

**Comment by Integralist** [comment]
👋🏻 Hi @Miniwoffer 

Thanks for taking the time to open this PR and for your patience waiting for a response.

We discussed this change internally yesterday and have decided not to accept the change.

The main reason was that falling back to TCP would add latency and change how `dnsr` detects the existence of domains. It would be normal for a top-level DNS client, like a CLI tool, to do the TCP retry but this should be in the caller’s code, not a default for all users of the `dnsr` library. 

The existing behaviour might not be perfect, and it's not that this proposed change doesn't provide value, it's just that it's not a use-case that should be auto-handled by the library itself.
 
Also, this library was originally designed for (and is used in production by) https://domainr.com/ so any changes that aren't directly relevant to Domainr need even more careful consideration.

Again, thank you for your PR. We really appreciate your interest in `dnsr`.

**Comment by Miniwoffer** [comment]
@Integralist Understandable, but if it is the library user's responsibility to do TCP retry they need some way of knowing the answer is truncated which is currently not the case.
You could add a "truncated" error, but that would probably break some applications.
I think a better solution is to introduce a Option.WithTCPRetry().

**Comment by Integralist** [comment]
@ydnar @cee-dub do you have thoughts on this? I agree, if there currently isn't a mechanism for identifying the result as being truncated then it would be good to surface that information to the caller.

**Comment by cee-dub** [comment]
Will need to think if there's a non-breaking API change that could surface the truncated flag from the header.

**Comment by Miniwoffer** [comment]
`Option.WithTCPRetry() `  Would be non-breaking!

**Comment by cee-dub** [comment]
The option sounds reasonable. Would you update the PR?

**Pull request closed without merging**
